server:
  port: 8080 # The port your Spring Boot app will run on

spring:
  application:
    name: notification-service

  # 1. PostgreSQL Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # 2. JPA / Hibernate Settings (Database tool)
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates DB tables based on your Java code
    show-sql: true # Prints SQL queries in the console so you can see what it's doing
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 3. Kafka Connection
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest # If the app crashes, it reads unread messages from the beginning
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*" # Allows Kafka to read our custom JSON objects

  # 4. Redis Connection
  data:
    redis:
      host: localhost
      port: 6379